-- understanding data
SELECT*FROM PROVIDERS;
SELECT*FROM RECEIVERS;
SELECT*FROM FOOD;
SELECT*FROM CLAIMS;

-- datatype conversion
ALTER TABLE FOOD
ALTER COLUMN EXPIRY_DATE TYPE DATE
USING TO_DATE(EXPIRY_DATE,'MM/DD/YYYY');

-- FOOD PROVIDERS AND RECEIVERS
--- 1.How many food providers and receivers are there in each city?
---- providers by city
SELECT CITY,COUNT(*) AS PROVIDERS
FROM PROVIDERS
GROUP BY 1
ORDER BY 2 DESC;
---- receivers by city
SELECT CITY, COUNT(*) AS RECEIVERS
FROM RECEIVERS
GROUP BY 1
ORDER BY 2 DESC;
---- providers and receivers by city
SELECT A.CITY, COUNT(A.CITY) AS PROVIDERS,COUNT(B.CITY) AS RECEIVERS
FROM PROVIDERS AS A
FULL JOIN RECEIVERS AS B
ON A.CITY=B.CITY
GROUP BY 1
ORDER BY 2 DESC;

--- 2.Which type of food provider (restaurant, grocery store, etc.) contributes the most food?
SELECT TYPE AS PROVIDER, COUNT(*)AS FOOD
FROM PROVIDERS
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

--- 3.What is the contact information of food providers in a specific city?
SELECT CITY, CONTACT
FROM PROVIDERS
GROUP BY 1,2
ORDER BY 1;

--- 4.Which receivers have claimed the most food?
---- receiver with most claimed food
SELECT RECEIVER FROM
(SELECT RECEIVER,RANK()OVER(ORDER BY FOOD DESC) AS RN FROM(
SELECT NAME AS RECEIVER, COUNT(*) AS FOOD
FROM RECEIVERS
GROUP BY 1
ORDER BY 2 DESC))
WHERE RN=1;
---- type of receiver with claimed most food
SELECT RECEIVER FROM
(SELECT RECEIVER,RANK()OVER(ORDER BY FOOD DESC) AS RN FROM(
SELECT type AS RECEIVER, COUNT(*) AS FOOD
FROM RECEIVERS
GROUP BY 1
ORDER BY 2 DESC))
WHERE RN=1;


-- FOOD LISTING AND AVAILABILITY
--- 5.What is the total quantity of food available from all providers?
SELECT SUM(QUANTITY) AS TOTAL_FOOD_QUANTITY
FROM FOOD;

--- 6.Which city has the highest number of food listings?
SELECT LOCATION AS CITY, COUNT(*) AS LISTING
FROM FOOD
GROUP BY 1 
ORDER BY 2 DESC
LIMIT 1;

--- 7.What are the most commonly available food types?
SELECT DISTINCT FOOD_TYPE
FROM FOOD;


-- CLAIMS AND DISTRIBUTION
--- 8.How many food claims have been made for each food item?
SELECT A.FOOD_NAME AS ITEM, COUNT(B.FOOD_ID) AS CLAIM
FROM FOOD AS A
JOIN CLAIMS AS B
ON A.FOOD_ID=B.FOOD_ID
GROUP BY 1;

--- 9.Which provider has had the highest number of successful food claims?
SELECT PROVIDER FROM
(SELECT A.NAME AS PROVIDER, COUNT(B.STATUS) AS CLAIM
FROM PROVIDERS AS A
JOIN FOOD AS C
ON A.PROVIDER_ID=C.PROVIDER_ID
JOIN CLAIMS AS B
ON C.FOOD_ID=B.FOOD_ID
WHERE B.STATUS='Completed'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

--- 10. What percentage of food claims are completed vs. pending vs. canceled?
WITH COMP AS (SELECT STATUS,COUNT(*) AS CLAIMS
              FROM CLAIMS
			  GROUP BY 1),
     TOT AS (SELECT COUNT(*) AS TOTAL FROM CLAIMS)
SELECT STATUS,ROUND((CLAIMS::NUMERIC/TOTAL)*100,2) AS PERCENTAGE
FROM COMP,TOT;


-- ANALYSIS AND INSIGHTS
--- 11. What is the average quantity of food claimed per receiver?
SELECT A.NAME AS RECEIVER,ROUND(AVG(C.QUANTITY),2) AS AVERAGE_QUANTITY
FROM RECEIVERS AS A
JOIN CLAIMS AS B
ON A.RECEIVER_ID=B.RECEIVER_ID
JOIN FOOD AS C
ON B.FOOD_ID=C.FOOD_ID
GROUP BY 1;

--- 12. Which meal type (breakfast, lunch, dinner, snacks) is claimed the most?
SELECT MEAL_TYPE FROM
(SELECT A.MEAL_TYPE,COUNT(*) AS CLAIMED
FROM FOOD AS A
JOIN CLAIMS AS B
ON A.FOOD_ID=B.FOOD_ID
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1);

--- 13.What is the total quantity of food donated by each provider?
SELECT A.NAME AS PROVIDER,SUM(B.QUANTITY) AS TOTAL_QUANTITY
FROM PROVIDERS AS A
JOIN FOOD AS B
ON A.PROVIDER_ID=B.PROVIDER_ID
GROUP BY 1;

--- 14. food claimed per day
SELECT EXTRACT(DAY FROM TIMESTAMP) AS DATE, COUNT(*) AS CLAIMS
FROM CLAIMS
GROUP BY 1
ORDER BY 1;

--- 15.expired food claimed
SELECT COUNT(*) AS EXPIRED
FROM FOOD AS A
JOIN CLAIMS AS B
ON A.FOOD_ID=B.FOOD_ID
WHERE A.EXPIRY_DATE<B.TIMESTAMP;